FIT5032_Project_EatSmart/Controllers/CalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FIT5032_Project_EatSmart.Controllers
{
    public class CalculatorController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

FIT5032_Project_EatSmart/Controllers/DiaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FIT5032_Project_EatSmart.Controllers
{
    
    public class DiaryController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetEvents()
        {
            using (DiaryEventEntities dc = new DiaryEventEntities())
            {
                var events = dc.Events.ToList();
                return new JsonResult { Data = events, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }

        [HttpPost]
        public JsonResult SaveEvent(Event e)
        {
            var status = false;
            using (DiaryEventEntities dc = new DiaryEventEntities())
            {
                if (e.EventId > 0)
                {
                    //Update the event
                    var v = dc.Events.Where(a => a.EventId == e.EventId).FirstOrDefault();
                    if (v != null)
                    {
                        v.Subject = e.Subject;
                        v.Start = e.Start;
                        v.End = e.End;
                        v.Description = e.Description;
                        v.IsFullDay = e.IsFullDay;
                        v.ThemeColor = e.ThemeColor;
                    }
                }
                else
                {
                    dc.Events.Add(e);
                }
                dc.SaveChanges();
                status = true;
            }
            return new JsonResult { Data = new { status = status } };
        }

        [HttpPost]
        public JsonResult DeleteEvent(int eventID)
        {
            var status = false;
            using (DiaryEventEntities dc = new DiaryEventEntities())
            {
                var v = dc.Events.Where(a => a.EventId == eventID).FirstOrDefault();
                if (v != null)
                {
                    dc.Events.Remove(v);
                    dc.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }

    }
}

FIT5032_Project_EatSmart/Controllers/FoodNutritionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FIT5032_Project_EatSmart.Models;

namespace FIT5032_Project_EatSmart.Controllers
{
    public class FoodNutritionsController : Controller
    {
        private FoodNutritionModdels db = new FoodNutritionModdels();

        // GET: FoodNutritions
        public ActionResult Index()
        {
            return View(db.FoodNutritions.ToList());
        }

        // GET: FoodNutritions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodNutrition foodNutrition = db.FoodNutritions.Find(id);
            if (foodNutrition == null)
            {
                return HttpNotFound();
            }
            return View(foodNutrition);
        }

        // GET: FoodNutritions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FoodNutritions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FoodName,Energy,Protein,TotalFat,Carbohydrates,TotalSugars,Calcium,Sodium,SaturatedFat")] FoodNutrition foodNutrition)
        {
            if (ModelState.IsValid)
            {
                db.FoodNutritions.Add(foodNutrition);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(foodNutrition);
        }

        // GET: FoodNutritions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodNutrition foodNutrition = db.FoodNutritions.Find(id);
            if (foodNutrition == null)
            {
                return HttpNotFound();
            }
            return View(foodNutrition);
        }

        // POST: FoodNutritions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FoodName,Energy,Protein,TotalFat,Carbohydrates,TotalSugars,Calcium,Sodium,SaturatedFat")] FoodNutrition foodNutrition)
        {
            if (ModelState.IsValid)
            {
                db.Entry(foodNutrition).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(foodNutrition);
        }

        // GET: FoodNutritions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodNutrition foodNutrition = db.FoodNutritions.Find(id);
            if (foodNutrition == null)
            {
                return HttpNotFound();
            }
            return View(foodNutrition);
        }

        // POST: FoodNutritions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FoodNutrition foodNutrition = db.FoodNutritions.Find(id);
            db.FoodNutritions.Remove(foodNutrition);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FIT5032_Project_EatSmart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Eat Smart</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            @Html.ActionLink("Eat Smart", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            @Html.ActionLink("Food Nutrition", "Index", "FoodNutritions", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Nutrition Calculator", "Index", "Calculator", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Forum", "Index", "Forum", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("My Food Diary", "Index", "Diary", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                @Html.ActionLink("Administration", "Index", "Admin", new { @class = "nav-link" })
                            </li>
                        }

                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
    </nav>
        <div class="container">
            <!-- Page Heading/Breadcrumbs -->
            <h1 class="mt-4 mb-3">
                @ViewBag.Title
                <small></small>
            </h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="@Url.Action("Index", "Home")">Home</a>
                </li>
                <li class="breadcrumb-item active">@ViewBag.Title</li>
            </ol>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p class="text-center">&copy; @DateTime.Now.Year - Eat Smart</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>