FIT5032_Project_EatSmart/Controllers/CalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FIT5032_Project_EatSmart.Controllers
{
    public class CalculatorController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

FIT5032_Project_EatSmart/Controllers/DiaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FIT5032_Project_EatSmart.Controllers
{
    
    public class DiaryController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetEvents()
        {
            using (DiaryEventEntities dc = new DiaryEventEntities())
            {
                var events = dc.Events.ToList();
                return new JsonResult { Data = events, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }

        [HttpPost]
        public JsonResult SaveEvent(Event e)
        {
            var status = false;
            using (DiaryEventEntities dc = new DiaryEventEntities())
            {
                if (e.EventId > 0)
                {
                    //Update the event
                    var v = dc.Events.Where(a => a.EventId == e.EventId).FirstOrDefault();
                    if (v != null)
                    {
                        v.Subject = e.Subject;
                        v.Start = e.Start;
                        v.End = e.End;
                        v.Description = e.Description;
                        v.IsFullDay = e.IsFullDay;
                        v.ThemeColor = e.ThemeColor;
                    }
                }
                else
                {
                    dc.Events.Add(e);
                }
                dc.SaveChanges();
                status = true;
            }
            return new JsonResult { Data = new { status = status } };
        }

        [HttpPost]
        public JsonResult DeleteEvent(int eventID)
        {
            var status = false;
            using (DiaryEventEntities dc = new DiaryEventEntities())
            {
                var v = dc.Events.Where(a => a.EventId == eventID).FirstOrDefault();
                if (v != null)
                {
                    dc.Events.Remove(v);
                    dc.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }

    }
}

FIT5032_Project_EatSmart/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FIT5032_Project_EatSmart.Controllers
{
    public class ForumController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

FIT5032_Project_EatSmart/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FIT5032_Project_EatSmart.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

    }
}

FIT5032_Project_EatSmart/Controllers/NutritionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FIT5032_Project_EatSmart.Controllers
{
    public class NutritionController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

FIT5032_Project_EatSmart/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FIT5032_Project_EatSmart/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<!-- Page Content -->
<div class="container">
    <!-- Content Row -->
    <div class="row">
        <!-- Map Column -->
        <div class="col-lg-8 mb-4">
            <!-- Embedded Google Map -->
            <iframe width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" style="border:0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3149.2853192632615!2d145.0420786153205!3d-37.87700967974094!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad6698cb33e0ac1%3A0x63f9134ad6bf7a0a!2sMonash+University!5e0!3m2!1sen!2sau!4v1536063379764"></iframe>
        </div>
        <!-- Contact Details Column -->
        <div class="col-lg-4 mb-4">
            <h3>Contact Details</h3>
            <p>
                900 Dandenong Rd,
                <br>Caulfield East VIC 3145
                <br>
            </p>
            <p>
                <abbr title="Phone">P</abbr>: (123) 456-7890
            </p>
            <p>
                <abbr title="Email">E</abbr>:
                <a href="mailto:name@example.com">
                    name@example.com
                </a>
            </p>
            <p>
                <abbr title="Hours">H</abbr>: Monday - Friday: 9:00 AM to 5:00 PM
            </p>
        </div>
    </div>
    <!-- /.row -->
    <!-- Contact Form -->
    <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
    <div class="row">
        <div class="col-lg-8 mb-4">
            <h3>Send us a Message</h3>
            <form name="sentMessage" id="contactForm" novalidate>
                <div class="control-group form-group">
                    <div class="controls">
                        <label>Full Name:</label>
                        <input type="text" class="form-control" id="name" required data-validation-required-message="Please enter your name.">
                        <p class="help-block"></p>
                    </div>
                </div>
                <div class="control-group form-group">
                    <div class="controls">
                        <label>Phone Number:</label>
                        <input type="tel" class="form-control" id="phone" required data-validation-required-message="Please enter your phone number.">
                    </div>
                </div>
                <div class="control-group form-group">
                    <div class="controls">
                        <label>Email Address:</label>
                        <input type="email" class="form-control" id="email" required data-validation-required-message="Please enter your email address.">
                    </div>
                </div>
                <div class="control-group form-group">
                    <div class="controls">
                        <label>Message:</label>
                        <textarea rows="10" cols="100" class="form-control" id="message" required data-validation-required-message="Please enter your message" maxlength="999" style="resize:none"></textarea>
                    </div>
                </div>
                <div id="success"></div>
                <!-- For success/fail messages -->
                <button type="submit" class="btn btn-primary" id="sendMessageButton">Send Message</button>
            </form>
        </div>
    </div>
    <!-- /.row -->
</div>
<!-- /.container -->

FIT5032_Project_EatSmart/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<header>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="/Images/download.png" alt="First slide">
                <div class="carousel-caption d-none d-md-block">
                    <h5>First slide</h5>
                    <p>...</p>
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="/Images/download.png" alt="Second slide">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Second slide</h5>
                    <p>...</p>
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="/Images/download.png" alt="Third slide">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Third slide</h5>
                    <p>...</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</header>
<!-- Page Content -->
<div class="container">
    <!-- Portfolio Section -->
    <h2>Find More...</h2>
    <div class="row">
        <div class="col-lg-3 col-sm-6 portfolio-item">
            <div class="card h-100">
                <a href="@Url.Action("Index", "Nutrition")"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                        Food Nutrition
                    </h4>
                    <p class="card-text">card-text</p>
                </div>
                <div class="card-footer">
                    @Html.ActionLink("Learn More", "Index", "Nutrition", new { area = "" }, new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6 portfolio-item">
            <div class="card h-100">
                <a href="@Url.Action("Index", "Calculator")"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                        Nutrition Calculator
                    </h4>
                    <p class="card-text">card-text</p>
                </div>
                <div class="card-footer">
                    @Html.ActionLink("Learn More", "Index", "Calculator", new { area = "" }, new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6 portfolio-item">
            <div class="card h-100">
                <a href="@Url.Action("Index", "Forum")"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                        Forum
                    </h4>
                    <p class="card-text">card-text</p>
                </div>
                <div class="card-footer">
                    @Html.ActionLink("Learn More", "Index", "Forum", new { area = "" }, new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6 portfolio-item">
            <div class="card h-100">
                <a href="@Url.Action("Index", "Forum")"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                        My Food Diary
                    </h4>
                    <p class="card-text">card-text</p>
                </div>
                <div class="card-footer">
                    @Html.ActionLink("Learn More", "Index", "Diary", new { area = "" }, new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>

        <!-- /.row -->
        <!-- Call to Action Section -->
        <div class="row mb-4">
            <div class="col-md-8">
                <br />
                <p>If you have a query after reading the information on our website there are a number of ways that you can contact us. Clinck on the contact us button to find more.</p>
            </div>
            <div class="col-md-4">
                <br />
                @Html.ActionLink("Contact Us", "Contact", "Home", new { area = "" }, new { @class = "btn btn-lg btn-secondary btn-block" })
            </div>
        </div>
    </div>
</div>